apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-server-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  rules:
  - host: demo.das.quest
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web
            port:
              name: http 
#             number: 8080/443/8443
  tls:
  - hosts:
    - demo.das.quest
    secretName: nginx-secret 

helm repo add bitnami https://charts.bitnami.com/bitnami
helm install my-release bitnami/argo-cd  --namespace argocd --create-namespace

kubectl expose deployment my-release-argo-cd-server --type=NodePort -n argocd --name my-release-argo-cd-nodeport
